### ISSUE TITLE
Calcite.cpp:241 Failed to start Calcite server [errno=2]: No such file or directory

### ISSUE THREAD

**Issue by jieguolove** [heavyai/heavydb#737]
[root@heavydb cpu20220218]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[root@heavydb ~]# wget https://releases.omnisci.com/os/tar/omnisci-os-latest-Linux-x86_64-cpu.tar.gz --no-check-certificate
--2022-05-08 17:48:53--  https://releases.omnisci.com/os/tar/omnisci-os-latest-Linux-x86_64-cpu.tar.gz
Resolving releases.omnisci.com (releases.omnisci.com)... 72.28.97.165
Connecting to releases.omnisci.com (releases.omnisci.com)|72.28.97.165|:443... connected.
WARNING: cannot verify releases.omnisci.com's certificate, issued by 鈥C=US/O=Let's Encrypt/CN=R3鈥

                                                                                                      Issued certificate has expired.
HTTP request sent, awaiting response... 200 OK
Length: 208123670 (198M) [application/octet-stream]
Saving to: 鈥榦mnisci-os-latest-Linux-x86_64-cpu.tar.gz鈥

100%[===================================================================================================================>] 208,123,670  607KB/s   in 14m 54s

2022-05-08 18:03:49 (227 KB/s) - 鈥榦mnisci-os-latest-Linux-x86_64-cpu.tar.gz鈥saved [208123670/208123670]
[root@heavydb ~]# mv omnisci-os-5.10.2-20220218-4112053580-Linux-x86_64-cpu cpu20220218
[root@heavydb ~]# cd cpu20220218/
[root@heavydb cpu20220218]# ll
total 60
drwxrwxr-x. 2 1004 1005   240 Feb 18 23:48 bin
-rw-r--r--. 1 1004 1005   653 Feb 18 23:07 common.thrift
-rw-r--r--. 1 1004 1005   306 Feb 18 23:07 completion_hints.thrift
drwxrwxr-x. 2 1004 1005    41 Feb 18 23:48 docker
-rwxr-xr-x. 1 1004 1005  2702 Feb 18 23:07 insert_sample_data
-rw-r--r--. 1 1004 1005 11383 Feb 18 23:07 LICENSE.md
drwxrwxr-x. 2 1004 1005    22 Feb 18 23:48 Logger
-rw-r--r--. 1 1004 1005    11 Feb 18 23:47 MAPD_GIT_HASH.txt
-rw-r--r--. 1 1004 1005 23456 Feb 18 23:07 omnisci.thrift
drwxrwxr-x. 2 1004 1005   177 Feb 18 23:48 QueryEngine
drwxr-xr-x. 3 1004 1005  4096 Feb 18 23:48 SampleCode
drwxrwxr-x. 2 1004 1005    26 Feb 18 23:48 scripts
drwxrwxr-x. 2 1004 1005    57 Feb 18 23:48 Shared
-rwxr-xr-x. 1 1004 1005  2700 Feb 18 23:07 startomnisci
drwxrwxr-x. 2 1004 1005   130 Feb 18 23:48 systemd
drwxrwxr-x. 5 1004 1005    58 Feb 18 23:48 ThirdParty
[root@heavydb cpu20220218]# pwd
/root/cpu20220218
[root@heavydb cpu20220218]# mkdir data && ./bin/initdb data
**2022-05-08T18:06:09.780485 F 8460 0 0 Calcite.cpp:241 Failed to start Calcite server [errno=2]: No such file or directory**

2022-05-08T18:06:40.801890 E 8460 0 0 Calcite.cpp:348 Problems connecting to Calcite. Thrift error - socket open() error: Connection refused
2022-05-08T18:06:40.907804 F 8460 0 0 Calcite.cpp:330 Could not connect to Calcite remote server running on port [3279]
Aborted

why???

**Comment by jieguolove** [comment]
solved:
execute
https://github.com/heavyai/heavydb/blob/master/scripts/mapd-deps-prebuilt.sh

**Comment by cdessanti** [comment]
Hi, 

As stated in the docs, a JRE is needed to start our database. 
It's not advisable to install all the deps needed to compile the software running the install deps script; just install a headless JRE this way

sudo apt install default-JRE-headless

**Comment by jieguolove** [comment]
> Hi,
> 
> As stated in the docs, a JRE is needed to start our database. It's not advisable to install all the deps needed to compile the software running the install deps script; just install a headless JRE this way
> 
> sudo apt install default-JRE-headless

ok,thanks!
