### ISSUE TITLE
Execute query without printing results to console

### ISSUE THREAD

**Issue by jiashenC** [heavyai/heavydb#741]
I am trying to do some performance study for HeavyDB. I wonder is there a way to disable results printing to console? 

In my case, the number of projected rows is high, so it can affect the runtime of the query.

**Comment by andrewseidl** [comment]
You could try either `\timing` inside a session or `heavysql --timing ...` to enable reporting of some basic timings from the server.

```
$ build/bin/heavysql --timing
User admin connected to database heavyai
heavysql> select count(*) from wi_parcels2;
EXPR$0
3520942
1 rows returned.
Execution time: 14 ms, Total time: 14 ms
```

`Execution time` is the amount spent doing actual calculations, `Total time` includes everything such as loading data from disk (if not already in memory), execution, preparing results, etc. These times are coming directly from the server, so you don't have to worry about network traffic, slow consoles printing results, etc.

I believe those timings are also exposed from our Python, Java, and Javascript connectors, though they might be a little hidden.

**Comment by jiashenC** [comment]
Close this issue for now.

I will go with `limit 0` for now as I try to automate different queries profiling.

**Comment by cdessanti** [comment]
MI think we will have something soon in the information schema, but in the meantime you can get some insights about the running time in the queries checking this post in the community's forum.

https://community.heavy.ai/t/tpc-h-data-loading/2547/6?u=candido.dessanti


Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
