### ISSUE TITLE
Build docker image from repository cmake version outdated

### ISSUE THREAD

**Issue by igor-suhorukov** [heavyai/heavydb#743]
I try to build heavydb by using docker image https://github.com/heavyai/heavydb/blob/master/docker/build/ubuntu1804/Dockerfile

`~/dev/projects/heavyai_docker$ docker run -it a24ccd22b007 /bin/bash
root@b40d9b6b23ed:/# git clone https://github.com/heavyai/heavydb.git
Cloning into 'heavydb'...
remote: Enumerating objects: 368513, done.
remote: Counting objects: 100% (470/470), done.
remote: Compressing objects: 100% (254/254), done.
remote: Total 368513 (delta 193), reused 438 (delta 192), pack-reused 368043
Receiving objects: 100% (368513/368513), 429.33 MiB | 923.00 KiB/s, done.
Resolving deltas: 100% (339967/339967), done.
root@b40d9b6b23ed:/# cd 
.dockerenv                boot/                     etc/                      lib/                      mnt/                      root/                     srv/                      usr/
NGC-DL-CONTAINER-LICENSE  dev/                      heavydb/                  lib64/                    opt/                      run/                      sys/                      var/
bin/                      docker-entrypoint.sh      home/                     media/                    proc/                     sbin/                     tmp/                      
root@b40d9b6b23ed:/# cd heavydb/
root@b40d9b6b23ed:/heavydb# ls
Analyzer        CMakePackaging.txt  Distributed  HeavyDB.cpp   Logger                   QueryEngine  SampleCode        StringOps      UdfCompiler              config               initdb.cpp          startheavy
Archive         Calcite             Doxyfile.in  ImportExport  MigrationMgr             QueryRunner  SampleData        TableArchiver  Utils                    docker               insert_sample_data  systemd
Benchmarks      Catalog             Embedded     L0Mgr         NvidiaComputeCapability  README.md    Shared            Tests          cmake                    docs                 java
CLA.txt         CudaMgr             Fragmenter   LICENSE.md    OSDependent              ROADMAP.md   SqliteConnector   ThirdParty     common.thrift            heavy.thrift         python
CMakeLists.txt  DataMgr             Geospatial   LockMgr       Parser                   SQLFrontend  StringDictionary  ThriftHandler  completion_hints.thrift  heavyai.conf.sample  scripts
root@b40d9b6b23ed:/heavydb# mkdir build
root@b40d9b6b23ed:/heavydb# cd build
root@b40d9b6b23ed:/heavydb/build# cmake -DCMAKE_BUILD_TYPE=debug ..
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.16 or higher is required.  You are running version 3.10.2

-- Configuring incomplete, errors occurred!
root@b40d9b6b23ed:/heavydb/build# make -j 4
make: *** No targets specified and no makefile found.  Stop.
root@b40d9b6b23ed:/heavydb/build# apt get cmake
E: Invalid operation get
root@b40d9b6b23ed:/heavydb/build# apt install cmake
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cmake is already the newest version (3.10.2-1ubuntu2.18.04.2).
`

**Comment by cdessanti** [comment]
Hi Igor,

Looking at the error you are getting.seems the the mapd-deps.sh hasn't run.

So run the mapd_deps.sh shell that's usually located into /usr/local/mapd-deps before run the cmake command.

This should solve your problem. 

Regards,
Candido

**Comment by igor-suhorukov** [comment]
Thank you @cdessanti 
It works for me with "source" command
